# -*- coding: utf-8 -*-
"""simple_harmonic_oscillator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j1bkXi9F2mJAedhkEggqdjXcf8n_ZoF1
"""

import numpy as np
import matplotlib.pyplot as plt

# --- Παράμετροι ---
m = 0.5       # Μάζα σε kg
k = 20.0      # Σταθερά ελατηρίου σε N/m
x0 = 0.2      # Αρχική απομάκρυνση (τέντωμα) σε μέτρα
t_max = 5.0   # Συνολικός χρόνος (δευτερόλεπτα)

# --- Υπολογισμοί ---
# Η κυκλική συχνότητα ω = sqrt(k/m)
omega = np.sqrt(k / m)

# Δημιουργία χρόνου από 0 έως t_max
t = np.linspace(0, t_max, 500)

# Εξίσωση κίνησης: x(t) = x0 * cos(ω*t)
x = x0 * np.cos(omega * t)

# --- Σχεδίαση Γραφήματος ---
plt.figure(figsize=(10, 5))
plt.plot(t, x, color='blue', linewidth=2, label='Θέση μάζας')

# Διακόσμηση γραφήματος
plt.title('Απλή Αρμονική Ταλάντωση (Σύστημα Μάζας-Ελατηρίου)')
plt.xlabel('Χρόνος (s)')
plt.ylabel('Απομάκρυνση x (m)')
plt.axhline(0, color='black', linestyle='--') # Θέση ισορροπίας
plt.grid(True, alpha=0.3)
plt.legend()



plt.show()